# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#'
NULL

addColumnOfOnes <- function(mat) {
    .Call(`_regressionhelper_addColumnOfOnes`, mat)
}

#'
NULL

getBetaHat <- function(mat, y) {
    .Call(`_regressionhelper_getBetaHat`, mat, y)
}

#'
NULL

getF <- function(mat, y) {
    .Call(`_regressionhelper_getF`, mat, y)
}

#'
NULL

getResidual <- function(mat, y) {
    .Call(`_regressionhelper_getResidual`, mat, y)
}

#'
NULL

getRsquare <- function(mat, y) {
    .Call(`_regressionhelper_getRsquare`, mat, y)
}

#'
NULL

getT <- function(mat, y) {
    .Call(`_regressionhelper_getT`, mat, y)
}

